server: "https://10.11.1.11:6443"
token: "<K3S_CLUSTER_TOKEN>"
node-name: "atius-srv-2"
node-ip: "10.12.1.12"
advertise-address: "10.12.1.12"
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
cluster-dns: "10.43.0.10"
cluster-domain: "cluster.local"
flannel-backend: "vxlan"
flannel-iface: "enp2s0"
write-kubeconfig-mode: "0600"
tls-san:
  - "10.11.1.11"
  - "10.12.1.12"
  - "10.13.1.13"
  - "atius-srv-1"
  - "atius-srv-2"
  - "atius-srv-3"
disable:
  - traefik
  - servicelb
secrets-encryption: true
