#!/bin/sh
set -eu

src="/usr/local/share/xrdp-abnt2"
dst="/etc/xrdp"

[ -d "$dst" ] || exit 0
[ -f "$src/xrdp_keyboard.ini" ] || exit 0
[ -f "$src/km-abnt2.ini" ] || exit 0
[ -f "$src/startwm.sh" ] || exit 0

install -o nobody -g nogroup -m 644 "$src/xrdp_keyboard.ini" "$dst/xrdp_keyboard.ini"
install -o nobody -g nogroup -m 644 "$src/km-abnt2.ini" "$dst/km-00000409.ini"
install -o nobody -g nogroup -m 644 "$src/km-abnt2.ini" "$dst/km-00000416.ini"
install -o nobody -g nogroup -m 644 "$src/km-abnt2.ini" "$dst/km-00010416.ini"
install -o nobody -g nogroup -m 644 "$src/km-abnt2.ini" "$dst/km-0000080a.ini"
install -o nobody -g nogroup -m 644 "$src/km-abnt2.ini" "$dst/km-0000f010.ini"
install -o nobody -g nogroup -m 755 "$src/startwm.sh" "$dst/startwm.sh"

xrdp_ini="$dst/xrdp.ini"
if [ -f "$xrdp_ini" ]; then
    ensure_override() {
        key="$1"
        value="$2"
        pattern=$(printf '%s' "$key" | sed 's/\./\\./g')
        if grep -Eq "^[#;]?[[:space:]]*${pattern}[[:space:]]*=" "$xrdp_ini"; then
            sed -Ei "s|^[#;]?[[:space:]]*${pattern}[[:space:]]*=.*|${key}=${value}|" "$xrdp_ini"
        else
            sed -i "/^\[Globals\]$/a ${key}=${value}" "$xrdp_ini"
        fi
    }
    ensure_override 'xrdp.override_keyboard_type' '0x04'
    ensure_override 'xrdp.override_keyboard_subtype' '0x00'
    ensure_override 'xrdp.override_keylayout' '0x00000416'
fi
