fullnameOverride: omni-monitoring

defaultRules:
  create: true

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: America/Sao_Paulo
  service:
    type: ClusterIP
  ingress:
    enabled: false
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  nodeSelector:
    kubernetes.io/hostname: atius-srv-1

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    nodeSelector:
      kubernetes.io/hostname: atius-srv-1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

prometheus:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  prometheusSpec:
    replicas: 1
    retention: 15d
    retentionSize: 18GiB
    serviceMonitorSelectorNilUsesHelmValues: true
    podMonitorSelectorNilUsesHelmValues: true
    nodeSelector:
      kubernetes.io/hostname: atius-srv-1
    resources:
      requests:
        cpu: 300m
        memory: 768Mi
      limits:
        cpu: "1"
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

kube-state-metrics:
  releaseLabel: true

nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    aix:
      enabled: false
    darwin:
      enabled: false

prometheus-node-exporter:
  releaseLabel: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
