apiVersion: v1
kind: LimitRange
metadata:
  name: pod-500m-strict
  labels:
    managed-by: omni-srv-admin
    atius.com/cpu-unit: pod-500m
spec:
  limits:
    - type: Pod
      max:
        cpu: 500m
